fos_rest:
  param_fetcher_listener:  true
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors
  allowed_methods_listener:  true
  view:
    view_response_listener:  true
  serializer:
    serialize_null: true