version: '3'

services:
  nginx:
    image: nginx:1.15.3-alpine
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/conf:/etc/nginx/conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-CAWuM6yT6xlHX2Es}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      - ./docker/database:/docker-entrypoint-initdb.d
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
